### ISSUE TITLE
error while cloning the repo

### ISSUE THREAD

**Issue by jonbonraki** [TejasQ/basically-streams#14] opened 2017-11-01 04:34 UTC
I have an issue with:
* I m seeing the following error while cloning the repo

![image](https://user-images.githubusercontent.com/8699057/32260141-0401e7f4-be94-11e7-9d4e-3c170a43b054.png)

**Comment by fridfinnurm** [comment] 2017-11-01 14:14
I'm reasonably sure this has to do with some ssh key malarkey.
You can still clone from `https://github.com/TejasQ/basically-streams.git` though :)

**Comment by TejasQ** [comment] 2017-11-01 14:53
Yeah, this actually seems to be an issue with your git setup on your machine, @jonbonraki! Closing this as it is unreproducable, unless someone else has the same issue/can provide steps to reproduce.

Thanks for the issue/feedback, regardless! Much appreciated. 😄

**Closed as completed by TejasQ** 2017-11-01 14:53 UTC
